### ISSUE TITLE
License and README.md

### ISSUE THREAD

**Issue by dima74** [Evgeny-SHL/MIPT-DIHT-Archive#1]
Hello! I have found that your project has no license attached. It is highly recommended for GitHub projects to have a license attached; otherwise people cannot legally use your project. Also it would be nice to attach some README.md with instructions about your project: how to execute, how to compile, how to contribute, etc.

**Comment by Evgeny-SHL** [comment]
Извините, я ничем не могу помочь: я не читаю сообщения на английском.
